// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cardId: __t.u64().primaryKey().name("card_id"),
  gameId: __t.u64().name("game_id"),
  word: __t.string(),
  position: __t.u32(),
  cardType: __t.string().name("card_type"),
  isRevealed: __t.bool().name("is_revealed"),
  revealedByTeam: __t.string().name("revealed_by_team"),
});
