// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  roomCode: __t.string().name("room_code"),
  status: __t.string(),
  currentTeam: __t.string().name("current_team"),
  currentPhase: __t.string().name("current_phase"),
  clueWord: __t.string().name("clue_word"),
  clueNumber: __t.i32().name("clue_number"),
  guessesRemaining: __t.i32().name("guesses_remaining"),
  guessesMade: __t.i32().name("guesses_made"),
  winner: __t.string(),
  firstTeam: __t.string().name("first_team"),
  redRemaining: __t.u32().name("red_remaining"),
  blueRemaining: __t.u32().name("blue_remaining"),
  createdAt: __t.u64().name("created_at"),
});
