// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.u64().primaryKey().name("player_id"),
  gameId: __t.u64().name("game_id"),
  identity: __t.identity(),
  name: __t.string(),
  team: __t.string(),
  role: __t.string(),
  isHost: __t.bool().name("is_host"),
  isConnected: __t.bool().name("is_connected"),
});
