// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Card = __t.object("Card", {
  cardId: __t.u64(),
  gameId: __t.u64(),
  word: __t.string(),
  position: __t.u32(),
  cardType: __t.string(),
  isRevealed: __t.bool(),
  revealedByTeam: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const Game = __t.object("Game", {
  gameId: __t.u64(),
  roomCode: __t.string(),
  status: __t.string(),
  currentTeam: __t.string(),
  currentPhase: __t.string(),
  clueWord: __t.string(),
  clueNumber: __t.i32(),
  guessesRemaining: __t.i32(),
  guessesMade: __t.i32(),
  winner: __t.string(),
  firstTeam: __t.string(),
  redRemaining: __t.u32(),
  blueRemaining: __t.u32(),
  createdAt: __t.u64(),
});
export type Game = __Infer<typeof Game>;

export const GameEvent = __t.object("GameEvent", {
  eventId: __t.u64(),
  gameId: __t.u64(),
  eventType: __t.string(),
  team: __t.string(),
  playerName: __t.string(),
  detail: __t.string(),
  createdAt: __t.u64(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Player = __t.object("Player", {
  playerId: __t.u64(),
  gameId: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  team: __t.string(),
  role: __t.string(),
  isHost: __t.bool(),
  isConnected: __t.bool(),
});
export type Player = __Infer<typeof Player>;

