// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateGameReducer from "../create_game_reducer";
import EndTurnReducer from "../end_turn_reducer";
import ForceEndGameReducer from "../force_end_game_reducer";
import GiveClueReducer from "../give_clue_reducer";
import JoinGameReducer from "../join_game_reducer";
import JoinTeamReducer from "../join_team_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import RandomizeTeamsReducer from "../randomize_teams_reducer";
import RevealCardReducer from "../reveal_card_reducer";
import SetRoleReducer from "../set_role_reducer";
import StartGameReducer from "../start_game_reducer";

export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type EndTurnParams = __Infer<typeof EndTurnReducer>;
export type ForceEndGameParams = __Infer<typeof ForceEndGameReducer>;
export type GiveClueParams = __Infer<typeof GiveClueReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type JoinTeamParams = __Infer<typeof JoinTeamReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type RandomizeTeamsParams = __Infer<typeof RandomizeTeamsReducer>;
export type RevealCardParams = __Infer<typeof RevealCardReducer>;
export type SetRoleParams = __Infer<typeof SetRoleReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;

